"""empty message

Revision ID: 124973340d5b
Revises: bf54cd1aee50
Create Date: 2022-02-11 16:34:44.453692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124973340d5b'
down_revision = 'bf54cd1aee50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortcuts', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # op.create_unique_constraint(None, 'shortcuts', ['session_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'shortcuts', type_='unique')
    op.drop_column('shortcuts', 'password_hash')
    # ### end Alembic commands ###
