"""empty message

Revision ID: 5c62590a1b11
Revises: 959175814ebf
Create Date: 2022-05-23 23:18:47.725601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c62590a1b11'
down_revision = '959175814ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortcuts', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortcuts', 'is_active')
    # ### end Alembic commands ###
