"""empty message

Revision ID: 959175814ebf
Revises: ebfcd33000ce
Create Date: 2022-05-05 00:30:19.534067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959175814ebf'
down_revision = 'ebfcd33000ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortcuts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shortcuts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shortcuts', type_='foreignkey')
    op.drop_column('shortcuts', 'user_id')
    # ### end Alembic commands ###
