"""empty message

Revision ID: 963341045ea3
Revises: b4d1f18a31fe
Create Date: 2022-05-05 00:29:24.643054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963341045ea3'
down_revision = 'b4d1f18a31fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortcuts', sa.Column('last_visited', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_shortcuts_last_visited'), 'shortcuts', ['last_visited'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortcuts_last_visited'), table_name='shortcuts')
    op.drop_column('shortcuts', 'last_visited')
    # ### end Alembic commands ###
