"""empty message

Revision ID: b4d1f18a31fe
Revises: 184fae9bcdee
Create Date: 2022-05-05 00:28:37.450418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d1f18a31fe'
down_revision = '184fae9bcdee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_shortcuts_created'), 'shortcuts', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortcuts_created'), table_name='shortcuts')
    # ### end Alembic commands ###
