"""empty message

Revision ID: bf54cd1aee50
Revises: 2488a6b5dfcf
Create Date: 2022-02-08 00:29:26.395815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf54cd1aee50'
down_revision = '2488a6b5dfcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortcuts', sa.Column('session_id', sa.String(length=40), nullable=True))
    #op.create_unique_constraint(None, 'shortcuts', ['session_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'shortcuts', type_='unique')
    op.drop_column('shortcuts', 'session_id')
    # ### end Alembic commands ###
